package com.coinlab.app.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.coinlab.app.ui.portfolio.PortfolioHolding
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ExportUtils {

    fun exportPortfolioToCsv(
        context: Context,
        holdings: List<PortfolioHolding>,
        currency: String
    ): Uri? {
        try {
            val dateFormat = SimpleDateFormat("yyyy-MM-dd_HH-mm", Locale.US)
            val fileName = "CoinLab_Portfolio_${dateFormat.format(Date())}.csv"
            val file = File(context.cacheDir, fileName)

            FileWriter(file).use { writer ->
                // Header
                writer.append("Coin,Symbol,Amount,Avg Buy Price ($currency),Current Price ($currency),Total Value ($currency),Total Cost ($currency),PnL ($currency),PnL %\n")

                // Data rows
                holdings.forEach { holding ->
                    writer.append(
                        "${holding.coinName}," +
                        "${holding.coinSymbol}," +
                        "${String.format(Locale.US, "%.8f", holding.totalAmount)}," +
                        "${String.format(Locale.US, "%.2f", holding.averageBuyPrice)}," +
                        "${String.format(Locale.US, "%.2f", holding.currentPrice)}," +
                        "${String.format(Locale.US, "%.2f", holding.totalValue)}," +
                        "${String.format(Locale.US, "%.2f", holding.totalCost)}," +
                        "${String.format(Locale.US, "%.2f", holding.pnl)}," +
                        "${String.format(Locale.US, "%.2f", holding.pnlPercentage)}\n"
                    )
                }

                // Summary
                val totalValue = holdings.sumOf { it.totalValue }
                val totalCost = holdings.sumOf { it.totalCost }
                val totalPnl = totalValue - totalCost
                val totalPnlPct = if (totalCost > 0) (totalPnl / totalCost) * 100 else 0.0

                writer.append("\n")
                writer.append("TOTAL,,,,," +
                        "${String.format(Locale.US, "%.2f", totalValue)}," +
                        "${String.format(Locale.US, "%.2f", totalCost)}," +
                        "${String.format(Locale.US, "%.2f", totalPnl)}," +
                        "${String.format(Locale.US, "%.2f", totalPnlPct)}\n"
                )
                writer.append("\nGenerated by CoinLab v4.0 on ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date())}\n")
            }

            return FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
        } catch (e: Exception) {
            return null
        }
    }

    fun shareFile(context: Context, uri: Uri, mimeType: String = "text/csv") {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Portföyü Paylaş"))
    }
}
